// Code generated by scripts/configgen from config_azure_sandbox.go; DO NOT EDIT.

package cli

import (
	"flag"
)

type fileAzureSandboxConfig struct {
	Subscription  string `yaml:"subscriptionId,omitempty"`
	ResourceGroup string `yaml:"resourceGroup,omitempty"`
	Group         string `yaml:"group,omitempty"`
	Region        string `yaml:"region,omitempty"`
	ClientID      string `yaml:"clientId,omitempty"`
	Disk          string `yaml:"disk,omitempty"`
	DiskID        string `yaml:"diskId,omitempty"`
}

const AzureSandboxConfigDefaultDisk string = "ubuntu"

func defaultAzureSandboxConfig() AzureSandboxConfig {
	return AzureSandboxConfig{
		Disk: AzureSandboxConfigDefaultDisk,
	}
}

// AzureSandboxConfigApplied records accepted assignments during one application.
type AzureSandboxConfigApplied struct {
	InputAccepted bool
}

func (cfg *AzureSandboxConfig) applyFile(file *fileAzureSandboxConfig, trusted bool) (AzureSandboxConfigApplied, error) {
	var applied AzureSandboxConfigApplied
	err := applyConfigFileOverlay(cfg, file, &applied, trusted, "azure-sandbox")
	return applied, err
}

func (cfg *AzureSandboxConfig) applyEnv() (AzureSandboxConfigApplied, error) {
	var applied AzureSandboxConfigApplied
	err := applyConfigEnvironment(cfg, &applied, 0, 7)
	return applied, err
}

// AzureSandboxConfigFlagValues holds parsed values; only visited flags are applied.
type AzureSandboxConfigFlagValues struct {
	Subscription  *string
	ResourceGroup *string
	Group         *string
	Region        *string
	ClientID      *string
	Disk          *string
	DiskID        *string
}

// RegisterAzureSandboxConfigFlags registers mechanical bindings without selecting a provider.
func RegisterAzureSandboxConfigFlags(fs *flag.FlagSet, defaults AzureSandboxConfig) AzureSandboxConfigFlagValues {
	var values AzureSandboxConfigFlagValues
	registerConfigFlags(fs, defaults, &values)
	return values
}

// Apply copies explicit flag values. Provider validation must run afterward.
func (values AzureSandboxConfigFlagValues) Apply(cfg *AzureSandboxConfig, fs *flag.FlagSet) (AzureSandboxConfigApplied, error) {
	var applied AzureSandboxConfigApplied
	err := applyConfigFlags(cfg, values, &applied, fs)
	return applied, err
}
